### ISSUE TITLE
Service Unavailable (Rosemary::Unavailable)

### ISSUE THREAD

**Issue by 5up3rD4n1** [sozialhelden/rosemary#16]
I get Service Unavailable (Rosemary::Unavailable) while testing the explample codes

**Comment by christoph-buente** [comment]
Are you using the sandbox or the production system? Did you have a look at
the osm status page? http://wiki.openstreetmap.org/wiki/Platform_Status

Super Dani notifications@github.com schrieb am Fr., 11. Dez. 2015 23:34:

**Comment by 5up3rD4n1** [comment]
Probably was a time out connection error, I guess the service was down while I was testing.

It's working now.

I had some problems with the library:
    1. http://www.rubydoc.info/gems/rosemary/0.4.4/Rosemary/Relation , the reference says you can get a new relation element without parameters, but there's no Relation initializer with no arguments.
    2. I don't know why you can use '<<' operator over the relation.member list and you can't do it with the relation.tags. I found it kind of inconsistent, because you can use '<<' operator over node.tags but not over relation.tags. 

I'm just saying because I tried to follow the reference docs to work in a project with this gem and wasted a lot of time founding why it wasn't working.

I hope not being bothering.

**Comment by christoph-buente** [comment]
I have to admit, that the relation part is a bit underdeveloped.

Thanks for pointing out the inconsistency. I'm not 100% sure why i have implemented this way. I forked the code from the OSM lib project.
